spring:
  application:
    name: SpringBootDemo
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${jdbc.url}
    username: ${jdbc.username}
    password: ${jdbc.password}
    driver-class-name: ${jdbc.driver}
    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  type-aliases-package: com.mulberry.entity
  configuration:
    map-underscore-to-camel-case: true


server:
  address: 0.0.0.0
  port: 8848


app:
  upload-dir: ${user.home}/Pictures/tempSaved